spring.application.name=Tbibi

### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/tbibiii?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password= 

### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

server.port=8088

app.jwt.secret=MySuperSecretKeyForJwtAuthSpringSecurity2026!
app.jwt.expiration-ms=3600000

### MAIL ###
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=firasabdeljaouad@gmail.com
spring.mail.password=oqcr qlmm runm btky
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

### ACTIVATION URL ###
application.mailing.frontend.activation-url=http://localhost:4200/activate-account