spring.application.name=Tbibi
### DATABASE ###
spring.datasource.url=jdbc:h2:mem:tbibi;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
### H2 Console (optional - for development only) ###
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
server.port=8088

app.jwt.secret=MySuperSecretKeyForJwtAuthSpringSecurity2026!
app.jwt.expiration-ms=3600000

### MAIL ###
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=firasabdeljaouad@gmail.com
spring.mail.password=oqcr qlmm runm btky
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

### ACTIVATION URL ###
application.mailing.frontend.activation-url=http://localhost:4200/activate-account
